# Assignment For Numpy

# 1: Difficulty Level Beginner 

###  Import the numpy package under the name np

In [1]:
import numpy as np

### Create a null vector of size 10 

In [3]:
array=np.zeros(10)

In [4]:
array

array([0., 0., 0., 0., 0., 0., 0., 0., 0., 0.])

### Create a vector with values ranging from 10 to 49 

In [22]:
array=np.arange(10, 50)

In [23]:
array

array([10, 11, 12, 13, 14, 15, 16, 17, 18, 19, 20, 21, 22, 23, 24, 25, 26,
       27, 28, 29, 30, 31, 32, 33, 34, 35, 36, 37, 38, 39, 40, 41, 42, 43,
       44, 45, 46, 47, 48, 49])

### Find the shape of previous array in question 3 

In [36]:
array=np.arange(10, 49).shape

In [37]:
array

(39,)

###  Print the type of the previous array in question 3 

In [43]:
nums=(10, 49)
nums=np.array(nums)
nums.ndim


1

### Print the numpy version and the configuration


In [44]:
print(np.__version__)
print(np.show_config())

1.18.1
blas_mkl_info:
    libraries = ['mkl_rt']
    library_dirs = ['C:/Users/Admin/anaconda3\\Library\\lib']
    define_macros = [('SCIPY_MKL_H', None), ('HAVE_CBLAS', None)]
    include_dirs = ['C:\\Program Files (x86)\\IntelSWTools\\compilers_and_libraries_2019.0.117\\windows\\mkl', 'C:\\Program Files (x86)\\IntelSWTools\\compilers_and_libraries_2019.0.117\\windows\\mkl\\include', 'C:\\Program Files (x86)\\IntelSWTools\\compilers_and_libraries_2019.0.117\\windows\\mkl\\lib', 'C:/Users/Admin/anaconda3\\Library\\include']
blas_opt_info:
    libraries = ['mkl_rt']
    library_dirs = ['C:/Users/Admin/anaconda3\\Library\\lib']
    define_macros = [('SCIPY_MKL_H', None), ('HAVE_CBLAS', None)]
    include_dirs = ['C:\\Program Files (x86)\\IntelSWTools\\compilers_and_libraries_2019.0.117\\windows\\mkl', 'C:\\Program Files (x86)\\IntelSWTools\\compilers_and_libraries_2019.0.117\\windows\\mkl\\include', 'C:\\Program Files (x86)\\IntelSWTools\\compilers_and_libraries_2019.0.117\\windows\\mkl\

### Print the dimension of the array in question 3 

In [77]:
print=np.arange(10,49)

In [78]:
print

array([10, 11, 12, 13, 14, 15, 16, 17, 18, 19, 20, 21, 22, 23, 24, 25, 26,
       27, 28, 29, 30, 31, 32, 33, 34, 35, 36, 37, 38, 39, 40, 41, 42, 43,
       44, 45, 46, 47, 48])

In [79]:
print.ndim

1

### Create a boolean array with all the True values

In [20]:
import numpy as np
array=np.array([1,2,3,10,4,10,4,5],dtype='bool')

In [21]:
array

array([ True,  True,  True,  True,  True,  True,  True,  True])

### Create a two dimensional array 

In [81]:
array=np.array([[1,2,3,4,5],[6,7,8,9,10]])

In [82]:
array

array([[ 1,  2,  3,  4,  5],
       [ 6,  7,  8,  9, 10]])

### Create a three dimensional array 

In [30]:
array=np.array([[[1,2,3,4,5],[6,7,8,9,10],[11,12,13,14,15]]])

In [31]:
array

array([[[ 1,  2,  3,  4,  5],
        [ 6,  7,  8,  9, 10],
        [11, 12, 13, 14, 15]]])

# 2: Difficulty Level Easy

### Reverse a vector (first element becomes last)

In [2]:
import numpy as np


In [15]:
array=np.arange(1,21)

In [16]:
array

array([ 1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15, 16, 17,
       18, 19, 20])

In [20]:
array_reverse=array[::-1]

In [21]:
array_reverse

array([20, 19, 18, 17, 16, 15, 14, 13, 12, 11, 10,  9,  8,  7,  6,  5,  4,
        3,  2,  1])

### Create a null vector of size 10 but the fifth value which is 1 

In [93]:
array_null=np.zeros(10)

In [95]:
array_null

array([0., 0., 0., 0., 0., 0., 0., 0., 0., 0.])

In [97]:
array_null[5]=1

In [98]:
array_null

array([0., 0., 0., 0., 0., 1., 0., 0., 0., 0.])

### Create a 3x3 identity matrix 

In [99]:
matrix3=np.identity(3)

In [100]:
matrix3

array([[1., 0., 0.],
       [0., 1., 0.],
       [0., 0., 1.]])

### arr = np.array([1, 2, 3, 4, 5]) 
### Convert the data type of the given array from int to float

In [101]:
array=np.array([1,2,3,4,5])

In [102]:
array

array([1, 2, 3, 4, 5])

In [103]:
array_float=(array.astype(float))

In [104]:
array_float

array([1., 2., 3., 4., 5.])

### Multiply arr1 with arr2 

In [105]:
arr1 = np.array([[1., 2., 3.],

            [4., 5., 6.]]) 

arr2 = np.array([[0., 4., 1.],

            [7., 2., 12.]])


In [106]:
array_mutilply=arr1*arr2

In [107]:
array_mutilply

array([[ 0.,  8.,  3.],
       [28., 10., 72.]])

### Make an array by comparing both the arrays provided above 

In [108]:
arr1 = np.array([[1., 2., 3.],

            [4., 5., 6.]]) 

arr2 = np.array([[0., 4., 1.],

            [7., 2., 12.]])


In [112]:
array_compare=arr1==arr2

In [113]:
array_compare

array([[False, False, False],
       [False, False, False]])

### Extract all odd numbers from arr with values(0-9) 

In [116]:
array=np.arange(0,9)

In [117]:
array

array([0, 1, 2, 3, 4, 5, 6, 7, 8])

In [144]:
array[array % 2 == 1]

array([1, 3, 5, 7])

### Replace all odd numbers to -1 from previous array 

In [147]:
array[array % 2 == 1]=-1

In [148]:
array

array([ 0, -1,  2, -1,  4, -1,  6, -1,  8])

### arr = np.arange(10)
### Replace the values of indexes 5,6,7 and 8 to 12 

In [151]:
array=np.arange(10)

In [152]:
array

array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

In [154]:
array[4:8:]=12

In [155]:
array

array([ 0,  1,  2,  3, 12, 12, 12, 12,  8,  9])

### Create a 2d array with 1 on the border and 0 inside 

In [157]:
array2d = np.ones((5,5))




In [158]:
array2d

array([[1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1.]])

In [159]:
array2d[1:-1,1:-1] = 0


In [160]:
array2d

array([[1., 1., 1., 1., 1.],
       [1., 0., 0., 0., 1.],
       [1., 0., 0., 0., 1.],
       [1., 0., 0., 0., 1.],
       [1., 1., 1., 1., 1.]])

# 3: Difficulty Level Medium

### Replace the value 5 to 12 

In [38]:
arr2d = np.array([[1, 2, 3],

            [4, 5, 6], 

            [7, 8, 9]])


In [44]:
array[array==5]=12

In [46]:
array

array([ 1,  2,  3,  4, -1,  6,  7,  8,  9])

### Convert all the values of 1st array to 64

In [59]:
import numpy as np
arr3d = np.array([[[1, 2, 3], [4, 5, 6]], [[7, 8, 9], [10, 11, 12]]])


In [60]:
arr3d

array([[[ 1,  2,  3],
        [ 4,  5,  6]],

       [[ 7,  8,  9],
        [10, 11, 12]]])

In [61]:
arr3d[0]

array([[1, 2, 3],
       [4, 5, 6]])

In [62]:
arr3d[0]=64

In [63]:
arr3d

array([[[64, 64, 64],
        [64, 64, 64]],

       [[ 7,  8,  9],
        [10, 11, 12]]])

### Make a 2-Dimensional array with values 0-9 and slice out the first 1st 1-D array from it 

In [235]:
array2d=np.array([[0,1,2,3,4],[5,6,7,8,9]])


In [237]:
array2d

array([[0, 1, 2, 3, 4],
       [5, 6, 7, 8, 9]])

In [238]:
array2d[0,0:]

array([0, 1, 2, 3, 4])

### Make a 2-Dimensional array with values 0-9 and slice out the 2nd value from 2nd 1-D array from it 

In [239]:
array2d=np.array([[0,1,2,3,4],[5,6,7,8,9]])

In [240]:
array2d

array([[0, 1, 2, 3, 4],
       [5, 6, 7, 8, 9]])

In [242]:
array2d[1,1]

6

### Create a 10x10 array with random values and find the minimum and maximum values 

In [245]:
array=np.random.rand(10,10)

In [246]:
array

array([[0.65315589, 0.59400873, 0.74979891, 0.51591113, 0.96870798,
        0.57995097, 0.41455097, 0.06001146, 0.89120581, 0.0676154 ],
       [0.99967832, 0.12770356, 0.62691551, 0.78627869, 0.17270407,
        0.30909582, 0.73307314, 0.20544066, 0.18622434, 0.70749271],
       [0.91819942, 0.59200181, 0.82176151, 0.19191002, 0.6351992 ,
        0.3700456 , 0.36381412, 0.97731999, 0.90042155, 0.85714779],
       [0.64208352, 0.40384302, 0.35668076, 0.46233281, 0.58394419,
        0.7214644 , 0.00525883, 0.54092717, 0.79239264, 0.45534713],
       [0.48481266, 0.74034853, 0.79111309, 0.91159668, 0.92355461,
        0.65983121, 0.17817075, 0.46921442, 0.92093886, 0.84969058],
       [0.49255158, 0.8676472 , 0.78972646, 0.95290272, 0.43573108,
        0.59714288, 0.1281704 , 0.9830586 , 0.15495449, 0.69891781],
       [0.24921388, 0.16847784, 0.14608868, 0.40695824, 0.15938474,
        0.29245432, 0.77452993, 0.08432306, 0.2322187 , 0.39498224],
       [0.80223594, 0.82504084, 0.8669094

In [248]:
np.min(array)

0.005258830304183504

In [249]:
np.max(array)

0.9996783163223477

### Find the common items between a and b 

In [250]:
#a = np.array([1,2,3,2,3,4,3,4,5,6]) b = np.array([7,2,10,2,7,4,9,4,9,8])

In [255]:
arraya=np.array([1,2,3,2,3,4,3,4,5,6])

In [256]:
arrayb=np.array([7,2,10,2,7,4,9,4,9,8])

In [257]:
arraya,arrayb

(array([1, 2, 3, 2, 3, 4, 3, 4, 5, 6]),
 array([ 7,  2, 10,  2,  7,  4,  9,  4,  9,  8]))

In [260]:
np.intersect1d(arraya, arrayb)

array([2, 4])

### Find the positions where elements of a and b match 

In [261]:
#a = np.array([1,2,3,2,3,4,3,4,5,6]) b = np.array([7,2,10,2,7,4,9,4,9,8])


In [264]:
arraya=np.array([1,2,3,2,3,4,3,4,5,6])
arrayb=np.array([7,2,10,2,7,4,9,4,9,8])


In [276]:
arraya,arrayb

(array([1, 2, 3, 2, 3, 4, 3, 4, 5, 6]),
 array([ 7,  2, 10,  2,  7,  4,  9,  4,  9,  8]))

In [281]:
np.where(arraya==arrayb)

(array([1, 3, 5, 7], dtype=int32),)

### Find all the values from array data where the values from array names are not equal to Will 

In [65]:
names = np.array(['Bob', 'Joe', 'Will', 'Bob', 'Will', 'Joe', 'Joe']) 


In [66]:
data = np.random.randn(7, 4)

In [67]:
names

array(['Bob', 'Joe', 'Will', 'Bob', 'Will', 'Joe', 'Joe'], dtype='<U4')

In [68]:
data

array([[-0.0632772 ,  1.0905701 ,  1.12407012, -0.49963125],
       [-0.83741922, -1.5427304 ,  1.61066463, -1.24902876],
       [-0.78704349, -0.42316406,  0.42318926, -0.92684055],
       [ 0.66633657,  0.64715703, -0.84979419,  1.37077439],
       [ 0.5011688 ,  1.22715868, -0.33894491,  0.28144363],
       [-1.05425396,  0.0062407 , -0.19830103, -1.81880246],
       [-1.0316356 ,  0.61597166,  0.56350703,  0.02058876]])

In [71]:
names=="Will"

array([False, False,  True, False,  True, False, False])

In [72]:
data[names=="Will"]

array([[-0.78704349, -0.42316406,  0.42318926, -0.92684055],
       [ 0.5011688 ,  1.22715868, -0.33894491,  0.28144363]])

# Difficulty Level Hard

### Create a 2D array of shape 5x3 to contain decimal numbers between 1 and 15. 

In [84]:
array_float=np.random.uniform(1,15, size=(5,3))

In [85]:
array_float

array([[11.90219097, 10.01600621, 11.41903774],
       [ 7.79119565,  7.44233614, 11.23716641],
       [ 7.23130099,  9.86373136, 13.8384149 ],
       [ 4.88684577,  4.45824551,  7.6516222 ],
       [10.88580141, 10.05317433,  8.16729738]])

### Create an array of shape (2, 2, 4) with decimal numbers between 1 to 16. 

In [87]:
array_float=np.random.uniform(1,16, size=(2,2,4))

In [88]:
array_float

array([[[ 2.43104443,  3.33970412, 10.35365649, 12.31262937],
        [14.69289806, 10.676587  , 14.38516074, 14.57687235]],

       [[10.24474073,  2.03986754, 11.94101593,  1.94312574],
        [14.78822495,  3.81809965,  7.48997201, 13.72758544]]])

### Swap axes of the array you created in Question 32 

In [92]:
#Create a 2D array of shape 5x3 to contain decimal numbers between 1 and 15

In [94]:
array_swap=np.random.uniform(1,15, size=(5,3))

In [95]:
array_swap

array([[ 1.95837898,  5.28884177, 10.28406469],
       [14.07250868,  3.33796603,  5.15180618],
       [ 7.48057522,  7.7631663 , 10.64987053],
       [ 9.1539699 ,  9.13772907, 13.25811942],
       [ 2.16866776, 11.5757407 ,  6.52084373]])

### Create an array of size 10, and find the square root of every element in the array, if the values less than 0.5, replace them with 0 

In [96]:
array=np.arange(10)

In [97]:
array

array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

In [99]:
array_sqroot=array**2

In [100]:
array_sqroot

array([ 0,  1,  4,  9, 16, 25, 36, 49, 64, 81], dtype=int32)

In [106]:
array[array_sqroot> 0.5]=0

In [107]:
array_sqroot

array([ 0,  1,  4,  9, 16, 25, 36, 49, 64, 81], dtype=int32)

### Create two random arrays of range 12 and make an array with the maximum values between each element of the two arrays 

In [112]:
array=np.random.randn(12).reshape(2,-1)

In [113]:
array

array([[ 0.83549904,  1.19595996, -0.41288552, -0.07912583,  0.45777628,
         0.79047633],
       [-0.83516786,  0.57021847, -0.11037084, -0.96433454, -0.07600348,
         1.2260507 ]])

In [117]:
np.max(array)

1.2260506966077411

In [115]:
array_max

<function ndarray.max>

### Find the unique names and sort them out! 

In [119]:
array_names = np.array(['Bob', 'Joe', 'Will', 'Bob', 'Will', 'Joe', 'Joe'])


In [120]:
np.unique(array_names)

array(['Bob', 'Joe', 'Will'], dtype='<U4')

### From array a remove all items present in array b 

In [121]:
a = np.array([1,2,3,4,5])
b = np.array([5,6,7,8,9])

In [126]:
result  = np.setdiff1d(a, b)

In [127]:
result

array([1, 2, 3, 4])

### Following is the input NumPy array delete column two and insert following new column in its place.
 

In [3]:
##sampleArray = numpy.array([[34,43,73],[82,22,12],[53,94,66]])
##newColumn = numpy.array([[10,10,10]])


In [4]:
import numpy as np


In [5]:
sampleArray = np.array([[34,43,73],[82,22,12],[53,94,66]])

In [6]:
sampleArray

array([[34, 43, 73],
       [82, 22, 12],
       [53, 94, 66]])

In [46]:
array=np.delete(sampleArray,2,1)

In [47]:
array

array([[34, 43],
       [82, 22],
       [53, 94]])

In [98]:
newColumn=np.array([[10, 10, 10]]).T

In [99]:
newColumn

array([[10],
       [10],
       [10]])

In [103]:
np.append(array,newColumn , axis=1)

array([[ 6., 23., 10.],
       [-1.,  7., 10.],
       [ 8.,  9., 10.]])

### Find the dot product of the above two matrix 

In [69]:
arrayx = np.array([[1., 2., 3.], [4., 5., 6.]])


In [70]:
arrayx

array([[1., 2., 3.],
       [4., 5., 6.]])

In [73]:
array = np.array([[6., 23.], [-1, 7], [8, 9]])

In [74]:
array 

array([[ 6., 23.],
       [-1.,  7.],
       [ 8.,  9.]])

In [75]:
dotproduct = np.dot(arrayx,array)

In [76]:
dotproduct

array([[ 28.,  64.],
       [ 67., 181.]])

### Generate a matrix of 20 random values and find its cumulative sum 

In [77]:
matrix=np.random.randn(20)

In [78]:
matrix

array([-0.65578117, -0.10270132, -1.57427999,  0.12220035, -0.89320888,
        1.80151383, -0.64912418, -0.92474992,  2.01023816, -0.02004675,
       -0.04607695,  0.85963675, -0.26385425, -1.88601182,  0.45880707,
        0.87983842, -1.25171897,  1.22333687,  0.64928588,  1.72286501])

In [79]:
np.cumsum(matrix)

array([-0.65578117, -0.75848249, -2.33276248, -2.21056213, -3.10377101,
       -1.30225718, -1.95138136, -2.87613128, -0.86589312, -0.88593987,
       -0.93201683, -0.07238008, -0.33623433, -2.22224615, -1.76343908,
       -0.88360066, -2.13531963, -0.91198276, -0.26269688,  1.46016813])